name       : libpng12
version    : 1.2.56
release    : 100
source     :
    - https://sourceforge.net/projects/libpng/files/libpng12/1.2.56/libpng-1.2.56.tar.xz : 24ce54581468b937734a6ecc86f7e121bc46a90d76a0d948dca08f32ee000dbe
homepage   : http://www.libpng.org/pub/png/libpng.html
license    :
    - Libpng
summary    : libpng12 (Binary Compatibility Library)
component  : binary.compat
builddeps  :
    - pkgconfig32(zlib)
    - libgcc-32bit
    - glibc-32bit-devel
description: |
    This package provides binary compatibility only. It is forbidden to build against it.
optimize   : speed
emul32     : yes
setup      : |
    %configure --disable-static --without-libpng-compat
build      : |
    %make
install    : |
    %make_install
    # Only ship libraries
    for i in /usr/bin /usr/share %libdir%/pkgconfig /usr/include; do
        rm -rfv "$installdir/$i"
    done
    # Forbid linking too
    rm $installdir/%libdir%/*.so
    # Skip any potential .la files
    rm -f $installdir/%libdir%/*.la || :
